- name: Setup Laravel [All Servers]
  hosts: all
  become: true

  roles:
    - geerlingguy.pip
    - geerlingguy.supervisor

- name: Setup Laravel [Application Servers]
  hosts: application
  become: true

  vars:
    php_version: '8.2'
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "localhost"
        documentroot: "/var/www/example"
        extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/example"

  roles:
    - geerlingguy.apache
    - name: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.apache-php-fpm
    - geerlingguy.php-memcached
    - geerlingguy.php-mysql
    - geerlingguy.php-redis
    - geerlingguy.nodejs

- name: Setup Laravel [Database Servers]
  hosts: database
  become: true

  vars:
    mysql_root_password: super-secure-password
    mysql_databases:
      - name: example
        encoding: latin1
        collation: latin1_general_ci
      - name: forge
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: forge
        host: "%"
        password: super-secure-password
        pric: "*:ALL"

  roles:
    - geerlingguy.mysql

- name: Setup Laravel [Cache Servers]
  hosts: cache
  become: true

  vars:
    redis_requirepass: "123123"

  roles:
    - geerlingguy.memcached
    - geerlingguy.redis