- name: Setup Laravel [All Servers]
  hosts: all
  become: true

  roles:
    - common
    - geerlingguy.pip
    - geerlingguy.supervisor

- name: Setup Laravel [Application Servers]
  hosts: application
  become: true

  vars:
    php_version: '8.1'
    php_enable_php_fpm: true
    php_webserver_daemon: "www-data"
    php_fpm_pool_user: "www-data"
    php_fpm_pool_group: "www-data"
    nginx_user: "www-data"
    nginx_error_log: "off"
    nginx_access_log: "off"
    php_fpm_pools:
      - pool_name: www
        pool_template: www.conf.j2
        pool_listen: "/var/run/php/php8.1-fpm.sock"
        pool_listen_allowed_clients: "192.168.1.162,127.0.0.1,0.0.0.0"
        pool_pm: dynamic
        pool_pm_max_children: 20
        pool_pm_start_servers: 2
        pool_pm_min_spare_servers: 1
        pool_pm_max_spare_servers: 3
        pool_pm_max_requests: 500
        pool_pm_status_path: ''
    nginx_vhosts:
      - listen: "80"
        server_name: "192.168.1.162"
        root: /var/www/example
        index: "index.php index.html"
        error_page: "404 /index.php"
        access_log: "/var/log/nginx/example/access.log combined"
        error_log: "/var/log/nginx/example/error.log"
        state: "present"
        extra_parameters: |
          location / {
            try_files $uri $uri/ /index.php?$query_string;
          }

          location = /favicon.ico { access_log off; log_not_found off; }
          location = /robots.txt  { access_log off; log_not_found off; }

          location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param   QUERY_STRING        $query_string;
            fastcgi_param   REQUEST_METHOD      $request_method;
            fastcgi_param   CONTENT_TYPE        $content_type;
            fastcgi_param   CONTENT_LENGTH      $content_length;
            fastcgi_param   SCRIPT_FILENAME     $realpath_root$fastcgi_script_name;
            fastcgi_param   SCRIPT_NAME     $fastcgi_script_name;
            fastcgi_param   REQUEST_URI     $request_uri;
            fastcgi_param   DOCUMENT_URI        $document_uri;
            fastcgi_param   DOCUMENT_ROOT       $realpath_root;
            fastcgi_param   SERVER_PROTOCOL     $server_protocol;
            fastcgi_param   GATEWAY_INTERFACE   CGI/1.1;
            fastcgi_param   SERVER_SOFTWARE     nginx/$nginx_version;
            fastcgi_param   REMOTE_ADDR     $remote_addr;
            fastcgi_param   REMOTE_PORT     $remote_port;
            fastcgi_param   SERVER_ADDR     $server_addr;
            fastcgi_param   SERVER_PORT     $server_port;
            fastcgi_param   SERVER_NAME     $server_name;
            fastcgi_param   HTTPS           $https if_not_empty;
            fastcgi_param   REDIRECT_STATUS     200;
            fastcgi_param   HTTP_PROXY  "";
          }

          location ~ /\.(?!well-known).* {
              deny all;
          }

  roles:
    - laravel
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-versions
    - geerlingguy.php-memcached
    - geerlingguy.php-mysql
    - geerlingguy.php-redis
    - geerlingguy.nodejs

- name: Setup Laravel [Database Servers]
  hosts: database
  become: true

  vars:
    mysql_root_password: super-secure-password
    mysql_databases:
      - name: example
        encoding: latin1
        collation: latin1_general_ci
      - name: forge
        encoding: latin1
        collation: latin1_general_ci
    mysql_users:
      - name: forge
        host: "%"
        password: super-secure-password
        pric: "*:ALL"

  roles:
    - geerlingguy.mysql

- name: Setup Laravel [Cache Servers]
  hosts: cache
  become: true

  vars:
    redis_requirepass: "123123"

  roles:
    - geerlingguy.memcached
    - geerlingguy.redis